version: "3.9"

services:
  database:
    image: postgres
    container_name: prova_web
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=ismael
      - POSTGRES_DB=ProvaSistemasWeb
    volumes:
      - pgdata:/data/postgres

  app:
    build: .
    container_name: api_prova
    ports:
      - 3333:3333
    volumes:
      - .:/usr/app
    links:
      - database
    depends_on:
      - database

volumes:
  pgdata:
    driver: local
